name:                sbu
version:             2.7.0
github:              "tssund93/sbu"
license:             BSD3
author:              "Travis"
maintainer:          "tssund93@gmail.com"
copyright:           "2018 Travis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tssund93/sbu#readme>

dependencies:
- base >= 4.7 && < 5
- Glob >= 0.10.0
- bytestring
- cereal
- containers
- directory
- exceptions
- filepath
- gitrev
- monadlist
- mtl
- optparse-applicative >= 0.16.1
- pipes
- prettyprinter
- prettyprinter-ansi-terminal
- text
- time

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall

executables:
  sbu:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - sbu

tests:
  tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - sbu
    - hspec
    - temporary
